logging:
  path: ./logs
spring:
  datasource:
    url: jdbc:mysql://107.6.61.149:3306/takeaway
    username: taojunyu
    password: az123123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

env:
  imageprefix: http://localhost:9220/takeaway/plaform/api/image/